package com.rkhamatyarov.laret.completion

import com.rkhamatyarov.laret.core.CliApp

class PowerShellCompletionGenerator : CompletionGenerator {
    override fun generate(app: CliApp): String {
        val appName = app.name
        val argD = "\$"

        val groupCases =
            app.groups.joinToString("\n") { group ->
                val commands =
                    group.commands.joinToString(",\n") { cmd ->
                        "                        '${cmd.name}'"
                    }
                "            '${group.name}' {\n" +
                    "                ${argD}completions = @(\n$commands\n                )\n" +
                    "            }"
            }

        val secondLevelCases =
            app.groups.joinToString("\n") { group ->
                val commands =
                    group.commands.joinToString(",\n") { cmd ->
                        "                        '${cmd.name}'"
                    }
                "            '${group.name}' {\n" +
                    "                ${argD}completions = @(\n$commands\n                )\n" +
                    "            }"
            }

        val allOptions =
            (
                listOf("'--help'", "'-h'", "'--version'", "'-v'") +
                    app.groups.flatMap { group ->
                        group.commands.flatMap { cmd ->
                            cmd.options.flatMap { opt ->
                                listOf("'--${opt.long}'", "'-${opt.short}'")
                            }
                        }
                    }
            ).distinct()

        val optionsStr = allOptions.joinToString(",\n") { "                        $it" }

        val topLevelGroups = app.groups.joinToString(",\n") { "            '${it.name}'" }
        val topLevelGroupsL2 = app.groups.joinToString(",\n") { "                    '${it.name}'" }

        return "# PowerShell completion for $appName\n" +
            "# Generated by Laret CLI framework\n" +
            "\n" +
            "${argD}scriptblock = {\n" +
            "    param(${argD}wordToComplete, ${argD}commandAst, ${argD}cursorPosition)\n" +
            "\n" +
            "    # Получаем только позиционные аргументы\n" +
            "    ${argD}command = ${argD}commandAst.ToString()\n" +
            "    ${argD}tokens = @(${argD}command -split '\\s+' | Where-Object { ${argD}_.Trim() })\n" +
            "\n" +
            "    ${argD}appIndex = -1\n" +
            "    for (${argD}i = 0; ${argD}i -lt ${argD}tokens.Count; ${argD}i++) {\n" +
            "        if (${argD}tokens[${argD}i] -eq '$appName' -or ${argD}tokens[${argD}i] -eq '$appName.exe') {\n" +
            "            ${argD}appIndex = ${argD}i\n" +
            "            break\n" +
            "        }\n" +
            "    }\n" +
            "\n" +
            "    if (${argD}appIndex -eq -1) {\n" +
            "        return\n" +
            "    }\n" +
            "\n" +
            "    ${argD}allArgs = @(${argD}tokens[(${argD}appIndex + 1)..(${argD}tokens.Count - 1)])\n" +
            "    ${argD}positionalArgs = @(${argD}allArgs | Where-Object { !${argD}_.StartsWith('-') })\n" +
            "    ${argD}argCount = ${argD}positionalArgs.Count\n" +
            "\n" +
            "    ${argD}completions = @()\n" +
            "\n" +
            "    if (${argD}argCount -eq 0) {\n" +
            "        # Top-level commands\n" +
            "        ${argD}completions = @(\n" +
            "$topLevelGroups\n" +
            "        )\n" +
            "    }\n" +
            "    elseif (${argD}argCount -eq 1) {\n" +
            "        # Subcommands based on group\n" +
            "        ${argD}group = ${argD}positionalArgs[0]\n" +
            "\n" +
            "        switch (${argD}group) {\n" +
            "$groupCases\n" +
            "            default {\n" +
            "                ${argD}completions = @(\n" +
            "$topLevelGroupsL2\n" +
            "                ) | Where-Object { ${argD}_ -like \"${argD}group*\" }\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "    elseif (${argD}argCount -eq 2) {\n" +
            "        ${argD}group = ${argD}positionalArgs[0]\n" +
            "\n" +
            "        switch (${argD}group) {\n" +
            "$secondLevelCases\n" +
            "            default {\n" +
            "                ${argD}completions = @(\n" +
            "$optionsStr\n" +
            "                )\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "    else {\n" +
            "        ${argD}completions = @(\n" +
            "$optionsStr\n" +
            "        )\n" +
            "    }\n" +
            "\n" +
            "    ${argD}completions |\n" +
            "        Where-Object { ${argD}_ -like \"${argD}wordToComplete*\" } |\n" +
            "        ForEach-Object {\n" +
            "            [System.Management.Automation.CompletionResult]::new(${argD}_, ${argD}_, 'ParameterValue', ${argD}_)\n" +
            "        }\n" +
            "}\n" +
            "\n" +
            "Register-ArgumentCompleter -CommandName $appName -ScriptBlock ${argD}scriptblock\n" +
            "Register-ArgumentCompleter -CommandName $appName.exe -ScriptBlock ${argD}scriptblock\n"
    }
}
