package com.rkhamatyarov.laret.completion

import com.rkhamatyarov.laret.core.CliApp

class PowerShellCompletionGenerator : CompletionGenerator {
    override fun generate(app: CliApp): String {
        val appName = app.name

        val groupCases =
            app.groups.joinToString("\n") { group ->
                val commands = group.commands.joinToString(",\n") { "                        '${it.name}'" }
                "                '${group.name}' {\n                    @(\n$commands\n                    )\n                }"
            }

        val allOptions =
            listOf("'--help'", "'-h'", "'--version'", "'-v'") +
                app.groups.flatMap { group ->
                    group.commands.flatMap { cmd ->
                        cmd.options.flatMap { opt ->
                            listOf("'--${opt.long}'", "'-${opt.short}'")
                        }
                    }
                }

        val optionsStr = allOptions.joinToString(",\n") { "                        $it" }

        return """
            |# PowerShell completion for $appName
            |# Generated by Laret CLI framework
            |
            |${'$'}scriptblock = {
            |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
            |    
            |    ${'$'}command = ${'$'}commandAst.ToString()
            |    ${'$'}tokens = @(${'$'}command -split '\s+' | Where-Object { ${'$'}_.Trim() })
            |    
            |    ${'$'}appIndex = -1
            |    for (${'$'}i = 0; ${'$'}i -lt ${'$'}tokens.Count; ${'$'}i++) {
            |        if (${'$'}tokens[${'$'}i] -eq '$appName' -or ${'$'}tokens[${'$'}i] -eq '$appName.exe') {
            |            ${'$'}appIndex = ${'$'}i
            |            break
            |        }
            |    }
            |    
            |    if (${'$'}appIndex -eq -1) {
            |        return
            |    }
            |    
            |    ${'$'}argCount = ${'$'}tokens.Count - ${'$'}appIndex - 1
            |    ${'$'}args = @(${'$'}tokens[(${'$'}appIndex + 1)..(${'$'}tokens.Count - 1)])
            |    ${'$'}completions = @()
            |    
            |    switch (${'$'}argCount) {
            |        0 {
            |            ${'$'}completions = @(
            |                ${app.groups.joinToString(",\n") { "                    '${it.name}'" }}
            |            )
            |        }
            |        1 {
            |            ${'$'}group = ${'$'}args[0]
            |            switch (${'$'}group) {
            |$groupCases
            |                default {
            |                    ${'$'}completions = @(
            |                        ${app.groups.joinToString(",\n") { "                        '${it.name}'" }}
            |                    ) | Where-Object { ${'$'}_ -like "${'$'}group*" }
            |                }
            |            }
            |        }
            |        default {
            |            ${'$'}completions = @(
            |$optionsStr
            |            )
            |        }
            |    }
            |    
            |    ${'$'}completions |
            |        Where-Object { ${'$'}_ -like "${'$'}wordToComplete*" } |
            |        ForEach-Object {
            |            [System.Management.Automation.CompletionResult]::new(${'$'}_, ${'$'}_, 'ParameterValue', ${'$'}_)
            |        }
            |}
            |
            |Register-ArgumentCompleter -CommandName $appName -ScriptBlock ${'$'}scriptblock
            |Register-ArgumentCompleter -CommandName $appName.exe -ScriptBlock ${'$'}scriptblock
            """.trimMargin()
    }
}
