package com.rkhamatyarov.laret.completion

import com.rkhamatyarov.laret.core.CliApp

class PowerShellCompletionGenerator : CompletionGenerator {
    override fun generate(app: CliApp): String {
        val appName = app.name

        val group =
            app.groups.joinToString("\n") { group ->
                val commands =
                    group.commands.joinToString(",\n") { cmd ->
                        "                        '${cmd.name}'"
                    }
                "            '${group.name}' {\n                \$completions = @(\n$commands\n                )\n            }"
            }

        val secondLevel =
            app.groups.joinToString("\n") { group ->
                val commands =
                    group.commands.joinToString(",\n") { cmd ->
                        "                        '${cmd.name}'"
                    }
                "            '${group.name}' {\n                \$completions = @(\n$commands\n                )\n            }"
            }

        val allOptions =
            listOf("'--help'", "'-h'", "'--version'", "'-v'") +
                app.groups.flatMap { group ->
                    group.commands.flatMap { cmd ->
                        cmd.options.flatMap { opt ->
                            listOf("'--${opt.long}'", "'-${opt.short}'")
                        }
                    }
                }

        val optionsStr = allOptions.distinct().joinToString(",\n") { "                        $it" }

        return """
            |# PowerShell completion for $appName
            |# Generated by Laret CLI framework
            |
            |${'$'}scriptblock = {
            |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
            |    
            |    ${'$'}command = ${'$'}commandAst.ToString()
            |    ${'$'}tokens = @(${'$'}command -split '\s+' | Where-Object { ${'$'}_.Trim() })
            |    
            |    ${'$'}appIndex = -1
            |    for (${'$'}i = 0; ${'$'}i -lt ${'$'}tokens.Count; ${'$'}i++) {
            |        if (${'$'}tokens[${'$'}i] -eq '$appName' -or ${'$'}tokens[${'$'}i] -eq '$appName.exe') {
            |            ${'$'}appIndex = ${'$'}i
            |            break
            |        }
            |    }
            |    
            |    if (${'$'}appIndex -eq -1) {
            |        return
            |    }
            |    
            |    # Получаем только позиционные аргументы (без флагов)
            |    ${'$'}allArgs = @(${'$'}tokens[(${'$'}appIndex + 1)..(${'$'}tokens.Count - 1)])
            |    ${'$'}positionalArgs = @(${'$'}allArgs | Where-Object { !${'$'}_.StartsWith('-') })
            |    ${'$'}argCount = ${'$'}positionalArgs.Count
            |    
            |    ${'$'}completions = @()
            |    
            |    if (${'$'}argCount -eq 0) {
            |        # Top-level commands
            |        ${'$'}completions = @(
            |${app.groups.joinToString(",\n") { "            '${it.name}'" }}
            |        )
            |    }
            |    elseif (${'$'}argCount -eq 1) {
            |        # Subcommands based on group
            |        ${'$'}group = ${'$'}positionalArgs[0]
            |        
            |        switch (${'$'}group) {
            |$group
            |            default {
            |                # Если группа не распознана, фильтруем группы по префиксу
            |                ${'$'}completions = @(
            |${app.groups.joinToString(",\n") { "                    '${it.name}'" }}
            |                ) | Where-Object { ${'$'}_ -like "${'$'}group*" }
            |            }
            |        }
            |    }
            |    elseif (${'$'}argCount -eq 2) {
            |        # Субкоманды для конкретной группы
            |        ${'$'}group = ${'$'}positionalArgs[0]
            |        
            |        switch (${'$'}group) {
            |$secondLevel
            |            default {
            |                # Неизвестная группа - флаги
            |                ${'$'}completions = @(
            |$optionsStr
            |                )
            |            }
            |        }
            |    }
            |    else {
            |        # Флаги для подкоманд и их параметры
            |        ${'$'}completions = @(
            |$optionsStr
            |        )
            |    }
            |    
            |    # Финальная фильтрация и форматирование
            |    ${'$'}completions |
            |        Where-Object { ${'$'}_ -like "${'$'}wordToComplete*" } |
            |        ForEach-Object {
            |            [System.Management.Automation.CompletionResult]::new(${'$'}_, ${'$'}_, 'ParameterValue', ${'$'}_)
            |        }
            |}
            |
            |Register-ArgumentCompleter -CommandName $appName -ScriptBlock ${'$'}scriptblock
            |Register-ArgumentCompleter -CommandName $appName.exe -ScriptBlock ${'$'}scriptblock
            """.trimMargin()
    }
}
