#!/bin/bash
# Bash completion for {{appName}}
# Generated by Laret CLI framework

_{{appName}}_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Generate list of top-level groups and commands
    local commands=(
{{#each items}}
        "{{item.name}}"
{{/each}}
    )

    # Generate list of all global and command-specific options
    local options=(
        "--help" "-h" "--version" "-v"
{{#each groups}}
{{#each item.commands}}
{{#each item.options}}
        "--{{item.long}}" "-{{item.short}}"
{{/each}}
{{/each}}
{{/each}}
    )

    # Logic to determine what to complete based on word count
    if [[ ${#COMP_WORDS[@]} -eq 2 ]]; then
        # Completing the first argument (the group/command)
        COMPREPLY=($(compgen -W "${commands[*]}" -- "$cur"))
    else
        # Completing an option or argument
        COMPREPLY=($(compgen -W "${options[*]}" -- "$cur"))
    fi
}

# Register the completion function for the application
complete -F _{{appName}}_complete {{appName}}
