#!/bin/bash
# Dynamic bash completion for {{appName}}
# Generated by Laret CLI framework
# Candidates are produced at runtime by `{{appName}} __complete`.

_{{appName}}_complete_dynamic() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local -a args=("${COMP_WORDS[@]:1:$((COMP_CWORD-1))}")
    local out directive=0 line value

    out=$("${COMP_WORDS[0]}" __complete "${args[@]}" "$cur" 2>/dev/null)

    COMPREPLY=()
    while IFS='' read -r line; do
        if [[ "$line" == :* ]]; then
            directive="${line#:}"
        elif [[ -n "$line" ]]; then
            value="${line%%$'\t'*}"
            COMPREPLY+=("$value")
        fi
    done <<< "$out"

    # NoSpace directive (bit 2): keep the cursor glued to the completion.
    if (( directive & 2 )); then
        compopt -o nospace 2>/dev/null
    fi
    # File-completion fallback unless NoFileComp (bit 4) is set.
    if (( ${#COMPREPLY[@]} == 0 )) && (( (directive & 4) == 0 )); then
        COMPREPLY=($(compgen -f -- "$cur"))
    fi
}

# Register the dynamic completion function for the application
complete -F _{{appName}}_complete_dynamic {{appName}}
