# Dynamic PowerShell completion for {{appName}}
# Generated by Laret CLI framework
# Candidates are produced at runtime by `{{appName}} __complete`.

Register-ArgumentCompleter -Native -CommandName '{{appName}}' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $elements = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() })
    if ($wordToComplete -and $elements.Count -gt 0) {
        # The partial word is the last element; the binary receives it separately.
        $elements = if ($elements.Count -gt 1) { @($elements[0..($elements.Count - 2)]) } else { @() }
    }

    $output = & '{{appName}}' __complete @elements "$wordToComplete" 2>$null
    foreach ($line in $output) {
        if ("$line".StartsWith(':')) { continue }
        if (-not "$line") { continue }
        $parts = "$line" -split "`t", 2
        $description = if ($parts.Count -gt 1) { $parts[1] } else { $parts[0] }
        [System.Management.Automation.CompletionResult]::new($parts[0], $parts[0], 'ParameterValue', $description)
    }
}
