# PowerShell completion for {{appName}}
# Generated by Laret CLI framework

$scriptblock = {
    param($wordToComplete, $commandAst, $cursorPosition)

    $command = $commandAst.ToString()
    # Split command into tokens
    $tokens = @($command -split '\s+' | Where-Object { $_.Trim() })

    # Find the index of the application name
    $appIndex = -1
    for ($i = 0; $i -lt $tokens.Count; $i++) {
        if ($tokens[$i] -eq '{{appName}}' -or $tokens[$i] -eq '{{appName}}.exe') {
            $appIndex = $i
            break
        }
    }

    if ($appIndex -eq -1) { return }

    # Extract arguments after the app name
    $allArgs = @($tokens[($appIndex + 1)..($tokens.Count - 1)])
    $positionalArgs = @($allArgs | Where-Object { !$_.StartsWith('-') })
    $argCount = $positionalArgs.Count

    $completions = @()

    if ($argCount -eq 0) {
        # Top-level completion: show groups
        $completions = @(
{{#each groups}}            '{{item.name}}'{{sep}}
{{/each}}        )
    }
    elseif ($argCount -eq 1) {
        # Second-level completion: show commands within a group
        $group = $positionalArgs[0]
        switch ($group) {
{{#each groups}}            '{{item.name}}' {
                $completions = @(
{{#each item.commands}}                        '{{item.name}}'{{sep}}
{{/each}}                )
            }
{{/each}}            default {
                # Fallback: show all groups if group is unknown
                $completions = @(
{{#each groups}}                    '{{item.name}}'{{sep}}
{{/each}}                ) | Where-Object { $_ -like "$group*" }
            }
        }
    }
    elseif ($argCount -eq 2) {
        # Third-level completion: show commands again if group is known, otherwise options
        $group = $positionalArgs[0]
        switch ($group) {
{{#each groups}}            '{{item.name}}' {
                $completions = @(
{{#each item.commands}}                        '{{item.name}}'{{sep}}
{{/each}}                )
            }
{{/each}}            default {
                $completions = @(
                    '--help', '-h', '--version', '-v',
{{#each globalOptions}}                    '--{{item.long}}', '-{{item.short}}'{{sep}}
{{/each}}                )
            }
        }
    }
    else {
        # Deeper levels: show options
        $completions = @(
            '--help', '-h', '--version', '-v',
{{#each globalOptions}}            '--{{item.long}}', '-{{item.short}}'{{sep}}
{{/each}}        )
    }

    # Filter, format, and return results
    $completions |
        Where-Object { $_ -like "$wordToComplete*" } |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}

# Register the completer for both the app name and app.exe
Register-ArgumentCompleter -CommandName {{appName}} -ScriptBlock $scriptblock
Register-ArgumentCompleter -CommandName {{appName}}.exe -ScriptBlock $scriptblock
