#compdef {{appName}}
# Zsh completion for {{appName}}
# Generated by Laret CLI framework

_{{appName}}() {
    local -a commands
    # Generate list of commands with descriptions
    commands=(
{{#each items}}
        '{{item.name}}:{{item.description}}'
{{/each}}
    )

    local -a options
    # Generate list of options with descriptions
    options=(
        '--help[Show help]' '-h[Show help]'
        '--version[Show version]' '-v[Show version]'
{{#each groups}}
{{#each item.commands}}
{{#each item.options}}
        '--{{item.long}}[{{item.description}}]' '-{{item.short}}[{{item.description}}]'
{{/each}}
{{/each}}
{{/each}}
    )

    # Use _describe for commands and _arguments for options
    _describe 'commands' commands
    _arguments "${options[@]}"
}
