#compdef {{appName}}
# Dynamic zsh completion for {{appName}}
# Generated by Laret CLI framework
# Candidates are produced at runtime by `{{appName}} __complete`.

_{{appName}}_complete_dynamic() {
    local -a candidates
    local line value desc directive=0 out

    out="$(${words[1]} __complete "${(@)words[2,CURRENT]}" 2>/dev/null)"

    while IFS='' read -r line; do
        if [[ "$line" == :* ]]; then
            directive="${line#:}"
        elif [[ -n "$line" ]]; then
            value="${line%%$'\t'*}"
            if [[ "$line" == *$'\t'* ]]; then
                desc="${line#*$'\t'}"
                candidates+=("${value}:${desc}")
            else
                candidates+=("${value}")
            fi
        fi
    done <<< "$out"

    if (( ${#candidates[@]} > 0 )); then
        _describe 'completions' candidates
    elif (( (directive & 4) == 0 )); then
        # File-completion fallback unless NoFileComp (bit 4) is set.
        _files
    fi
}

# Register only when the completion system is initialised (compinit run);
# when this file sits in $fpath the #compdef header handles registration.
if (( ${+functions[compdef]} )); then
    compdef _{{appName}}_complete_dynamic {{appName}}
fi
