package ${packageName}

import com.rkhamatyarov.laret.dsl.cli
import ${packageName}.commands.helloCommand
import kotlin.system.exitProcess

fun main(args: Array<String>) {
    val app = cli(
        name = "${appName}",
        version = "0.1.0",
        description = "${appName} — generated by laret new",
    ) {
        group(name = "hello", description = "Greeting demo with 12-factor config") {
            helloCommand()
        }
    }
    exitProcess(app.run(args))
}
